/* Cadernex — 50 lições "Do corre ao negócio". Trilha 1 é grátis; as outras são para Apoiadores. */
const TRILHAS=[
{t:"Dinheiro na mão",s:"A regra dos 10% e o básico que muda tudo",livre:true,l:[
 ["Pague você primeiro","Antes de pagar qualquer conta, separe 10% de tudo que ganhar. Esse dinheiro é seu e não se toca. É a primeira lição do Homem Mais Rico da Babilônia, e funciona até com pouco.","Separe 10% do que você ganhou hoje, mesmo que sejam R$ 8."],
 ["Um lugar só pros 10%","Dinheiro misturado some sem você perceber. Os 10% precisam de um lugar separado, longe do cartão de débito.","Crie uma caixinha ou conta separada no seu banco só pro cofre."],
 ["Saiba pra onde vai cada real","Não dá pra cortar gasto que você não enxerga. Anotar 30 dias seguidos mostra onde o dinheiro escorre.","Anote no Cadernex todo gasto de hoje, até o café."],
 ["Faça o dinheiro trabalhar","Dinheiro parado na conta perde valor. O que você guarda deve render num lugar seguro, que deixa sacar quando precisar.","Pesquise no app do seu banco o Tesouro Selic ou um CDB com liquidez diária."],
 ["Proteja o que você juntou","Quem promete dobrar seu dinheiro rápido quer o seu dinheiro. Só coloque grana no que você entende.","Leia o passo 5 do Dinheiro do Corre sobre golpes."],
 ["Diminua os custos fixos","Conta que vem todo mês pesa mais que gasto de vez em quando. Plano de celular, assinaturas e juros são os primeiros a revisar.","Liste suas contas fixas e corte uma que você quase não usa."],
 ["Garanta o seu futuro","Moto é profissão de risco. Sem INSS e sem reserva, um acidente zera a renda da família.","Veja o passo 3 do Dinheiro do Corre sobre MEI e INSS."],
 ["Aumente o quanto você vale","Quanto mais você sabe, mais você ganha. Estudar é o investimento que ninguém tira de você.","Escolha um curso grátis do Sebrae ou da sua faculdade pra começar este mês."],
 ["Dívida cara primeiro","Cartão de crédito e cheque especial cobram juros altíssimos. Nenhum investimento rende mais do que isso custa.","Veja quanto de juros você paga por mês e comece pela dívida mais cara."],
 ["Meta com número e data","\"Juntar dinheiro\" não é meta. \"Juntar R$ 1.000 até março\" é. Número e data fazem você agir.","Escreva uma meta com valor e data e coloque na meta da semana do Cadernex."]]},
{t:"Da moto ao CNPJ",s:"Trabalhar por conta própria como empresa",l:[
 ["Por que virar MEI","Com CNPJ você contribui pro INSS, emite nota, abre conta PJ e consegue crédito com juros menores.","Entre no gov.br e veja a lista de atividades do MEI."],
 ["Separe você da empresa","Misturar o dinheiro da casa com o do trabalho esconde se você está lucrando. Pague a si mesmo um valor fixo.","Defina um \"salário\" semanal pra você e deixe o resto na conta do trabalho."],
 ["Nota fiscal abre portas","Empresas e comércios maiores pagam melhor, mas pedem nota. Como MEI, você emite pelo portal do governo.","Faça login no Emissor Nacional de NFS-e pra conhecer a tela."],
 ["Preço começa no custo","Se você não sabe quanto custa rodar 1 km, pode estar trabalhando no prejuízo sem saber.","Some gasolina e manutenção do mês e divida pelos km rodados."],
 ["O custo escondido da moto","Pneu, óleo, relação e a moto perdendo valor também são custo. Quem esquece disso cobra barato demais.","Anote no Cadernex a última manutenção e quanto custou."],
 ["Fundo de manutenção","Manutenção não é surpresa, ela sempre chega. Guardando um pouco por dia, ela não vira emergência.","Guarde R$ 5 a R$ 10 por dia rodado num lugar separado."],
 ["Combine por escrito","Com cliente fixo, deixe claro o valor, o horário, o que está incluso e quando paga. Uma mensagem no WhatsApp já serve.","Mande pro seu cliente fixo um resumo do que vocês combinaram."],
 ["Receba do jeito certo","Pix com QR Code na conta do trabalho facilita o controle e passa confiança pro cliente.","Crie uma chave Pix aleatória pra receber dos clientes."],
 ["Seguro: faça a conta","Seguro da moto e seguro de vida custam dinheiro, mas uma perda sem seguro pode custar anos de trabalho.","Peça duas cotações de seguro e compare com o valor da sua moto."],
 ["Declaração em dia","MEI tem que entregar a declaração anual (DASN-SIMEI) até 31 de maio, mesmo sem faturar muito.","Coloque um lembrete no celular pra maio."]]},
{t:"Ideias de negócio",s:"O que dá pra montar com o que você já conhece da rua",l:[
 ["Entregador do bairro","Comércio pequeno paga taxa alta pros aplicativos. Você pode oferecer entrega direta por um preço justo, sem intermediário.","Visite 3 comércios perto de casa e ofereça entrega própria."],
 ["Rota fixa mensal","Farmácia, padaria e restaurante precisam de entrega todo dia. Um contrato mensal dá renda garantida.","Monte uma proposta simples: horários, área e valor por mês."],
 ["Documentos e malotes","Escritórios, contadores e cartórios precisam levar papel de um lado pro outro, e pagam bem por pontualidade.","Liste 5 escritórios na sua região e ofereça o serviço."],
 ["Grupo de motoboys","Sozinho você atende pouco. Um grupo organizado atende um comércio inteiro e ninguém fica parado.","Chame 2 colegas de confiança e conversem sobre dividir clientes."],
 ["Venda o que o motoboy usa","Capa de chuva, suporte de celular, baú, luva. Você conhece o produto e o cliente melhor que qualquer loja.","Pesquise o preço de 3 itens no atacado e no varejo."],
 ["Parceria com oficina","Você indica clientes pra uma oficina de confiança e ganha desconto ou comissão.","Converse com o dono da oficina que você usa."],
 ["Comida de casa","Marmita ou lanche feito pela família, com entrega sua. Comece pequeno e procure saber as regras da vigilância sanitária da sua cidade.","Faça 5 marmitas de teste e venda pra conhecidos."],
 ["Do campo pra mesa","Com o que você vai aprender em agronomia: cesta de verduras direto do produtor, entregue por assinatura. Você conhece as rotas e vai conhecer o produtor.","Descubra uma feira ou produtor perto da sua cidade."],
 ["Leva e traz","Idosos e famílias ocupadas pagam pra alguém buscar remédio, pagar conta ou fazer compra. Confiança é o produto.","Ofereça o serviço num grupo do seu bairro."],
 ["Teste antes de investir","Antes de gastar com estoque ou equipamento, venda pra 10 clientes. Se não vender pra 10, não vai vender pra 100.","Escolha uma ideia desta trilha e consiga o primeiro cliente."]]},
{t:"Vender e divulgar",s:"Como conseguir e manter cliente",l:[
 ["WhatsApp Business","É grátis e tem catálogo, mensagem automática e etiquetas pra separar clientes.","Instale o WhatsApp Business e monte o catálogo."],
 ["Apareça no Google","Com o perfil de empresa do Google, grátis, você aparece no mapa quando alguém procura entrega na sua região.","Crie o perfil da sua empresa no Google."],
 ["Mostre o trabalho","Fotos reais de entregas feitas, sem mostrar o cliente, e mensagens de clientes satisfeitos (com permissão) passam confiança.","Peça pra um cliente fixo um depoimento curto."],
 ["Cartão com QR Code","Um cartãozinho no caixa do comércio com seu WhatsApp em QR Code trabalha por você o dia todo.","Faça um modelo grátis no Canva e imprima 50."],
 ["Indicação vale ouro","Cliente satisfeito indica. Dê um desconto pra quem traz cliente novo.","Ofereça 10% de desconto na próxima entrega pra quem indicar."],
 ["Pontualidade é propaganda","Chegar no horário, todo dia, é o que faz o cliente não trocar você por ninguém.","Anote seus atrasos da semana e descubra a causa."],
 ["Responda rápido","Quem responde primeiro geralmente fecha. Mensagem automática ajuda quando você está pilotando.","Configure a mensagem de ausência do WhatsApp Business."],
 ["Tabela clara","Preço claro evita discussão e passa profissionalismo. Por distância, por hora ou por pacote.","Monte sua tabela de preços numa imagem simples."],
 ["Cuide do cliente fixo","Conquistar cliente novo custa bem mais do que manter o que você já tem. Um obrigado faz diferença.","Mande uma mensagem de agradecimento pros seus 3 melhores clientes."],
 ["Saiba dizer não","Cliente que sempre atrasa pagamento ou pede demais pelo mesmo preço dá prejuízo. Libere espaço pro cliente bom.","Veja qual cliente te dá mais trabalho por menos dinheiro."]]},
{t:"Crescer com segurança",s:"Quando o negócio começa a andar",l:[
 ["Reinvista uma parte","Coloque parte do lucro de volta no negócio, mas não tudo. Você também precisa viver e guardar.","Defina: quanto do lucro volta pro negócio e quanto é seu."],
 ["Os 10% continuam","Ganhou mais? Os 10% continuam, agora maiores. Quem para de guardar quando cresce volta pro zero na primeira crise.","Confira no cofre do Cadernex se você manteve os 10% este mês."],
 ["Cuidado com empréstimo","Não pegue empréstimo pra testar uma ideia. Se precisar crescer, compare o CET (custo total) e procure microcrédito com juros baixos.","Pesquise as linhas de microcrédito do seu banco e compare o CET."],
 ["Contratar ajuda","Ter alguém trabalhando pra você traz obrigações trabalhistas. O MEI pode ter 1 empregado registrado. Faça do jeito certo.","Leia as regras de contratação do MEI no portal do governo."],
 ["O limite do MEI","O MEI fatura até R$ 81 mil por ano. Chegando perto, é hora de planejar a mudança pra microempresa.","Some o que você faturou este ano até agora."],
 ["Quando chamar um contador","No começo, o MEI você faz sozinho. Quando crescer, o contador economiza mais do que custa.","Anote suas dúvidas sobre imposto pra levar numa consulta."],
 ["Você é o motor","Sem saúde não tem negócio. Sono, comida e cuidado com o corpo fazem parte do plano.","Veja a aba Corpo e ajuste uma coisa na sua rotina."],
 ["Nunca pare de aprender","Faculdade, cursos grátis do Sebrae e vídeos de quem já fez. Cada coisa nova é uma porta.","Faça uma aula grátis do Sebrae esta semana."],
 ["Ande com quem faz","Grupos de empreendedores, feiras e eventos do Sebrae abrem contatos e clientes.","Procure um evento de empreendedorismo na sua cidade."],
 ["Revise todo mês","Uma vez por mês, olhe os números do Cadernex: quanto ganhou, gastou, guardou e o que dá pra melhorar.","Marque no calendário o dia da sua revisão mensal."]]}
];
